version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JITSI_VPAAS_MAGIC_COOKIE=${JITSI_VPAAS_MAGIC_COOKIE}
    depends_on:
      - db
      - meilisearch
    networks:
      - app-network

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TicketFlow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  meilisearch:
    image: getmeili/meilisearch:v1.9.0
    volumes:
      - meilisearch-data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-dev_key_placeholder}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  meilisearch-data: