name: TicketFlow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql

      - name: Set up Environment Variables
        run: |
          echo "APP_NAME=TicketFlow" >> $GITHUB_ENV
          echo "APP_ENV=testing" >> $GITHUB_ENV
          echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> $GITHUB_ENV
          echo "APP_URL=http://localhost" >> $GITHUB_ENV
          echo "DB_CONNECTION=mysql" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_DATABASE=test_db" >> $GITHUB_ENV
          echo "DB_USERNAME=ci_user" >> $GITHUB_ENV  # Use new MySQL user
          echo "DB_PASSWORD=ci_password" >> $GITHUB_ENV  # Use new MySQL user password
          echo "SCOUT_DRIVER=meilisearch" >> $GITHUB_ENV
          echo "MEILISEARCH_HOST=http://localhost:7700" >> $GITHUB_ENV
          echo "MEILISEARCH_KEY=aSampleMasterKey" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=" >> $GITHUB_ENV
          echo "JITSI_VPAAS_MAGIC_COOKIE=" >> $GITHUB_ENV


      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-cache-${{ hashFiles('composer.lock') }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set up MySQL
        run: |
          sudo service mysql start
          # Create a new MySQL user for CI
          sudo mysql -e "CREATE USER 'ci_user'@'localhost' IDENTIFIED BY 'ci_password';"
          # Grant all privileges to the ci_user for the test_db database
          sudo mysql -e "GRANT ALL PRIVILEGES ON test_db.* TO 'ci_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          # Create the test database
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"



      - name: Install and Start Meilisearch
        run: |
          curl -L https://install.meilisearch.com | sh
          nohup ./meilisearch --master-key "aSampleMasterKey" > meilisearch.log 2>&1 &

      - name: Run Migrations
        run: php artisan migrate --env=testing

      - name: Scout Import for Meilisearch
        run: php artisan scout:import "App\Models\Ticket"

      - name: Run Pest Tests
        run: ./vendor/bin/pest