name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'database/migrations/**'
      - '**.php'
      - 'composer.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'database/migrations/**'
      - '**.php'
      - 'composer.lock'

concurrency:
  group: ci-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  verify-secrets:
    name: Verify Required Secrets
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      secrets_valid: ${{ steps.validate-secrets.outputs.secrets_valid }}
    steps:
      - id: validate-secrets
        name: Validate Secrets
        run: |
          required_secrets=("GEMINI_API_KEY" "JITSI_VPAAS_MAGIC_COOKIE")
          missing_secrets=()
          
          for secret in "${required_secrets[@]}"; do
            if [ -z "${{ secrets[secret] }}" ]; then
              missing_secrets+=("$secret")
            fi
          done
          
          if [ ${#missing_secrets[@]} -eq 0 ]; then
            echo "All required secrets are present"
            echo "secrets_valid=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Missing required secrets: ${missing_secrets[*]}"
            exit 1
          fi

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: verify-secrets
    if: needs.verify-secrets.outputs.secrets_valid == 'true'
    env:
      APP_KEY: base64:$(php -r 'echo base64_encode(random_bytes(32));')
      APP_NAME: TicketFlow
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test_db
      DB_USERNAME: test_user
      DB_PASSWORD: test_password
      MEILISEARCH_HOST: http://localhost:7700
      MEILISEARCH_KEY: aSampleMasterKey

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

      meilisearch:
        image: getmeili/meilisearch:v1.11.1
        env:
          MEILI_MASTER_KEY: aSampleMasterKey
        ports:
          - 7700:7700
        options: >
          --health-cmd="curl -f http://localhost:7700/health || exit 1"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.2-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.2-

      - name: Install Composer Dependencies
        run: |
          echo "Installing Composer dependencies..."
          if ! composer install --prefer-dist --no-progress; then
            echo "::error::Composer installation failed! Check composer.lock for conflicts."
            exit 1
          fi
          echo "Composer dependencies installed successfully."

      - name: Run Database Migrations
        run: |
          echo "Running database migrations..."
          if ! php artisan migrate:fresh --env=testing --force; then
            echo "::error::Database migrations failed! Check migration files and database connection."
            exit 1
          fi
          echo "Database migrations completed successfully."

      - name: Run Test Suite
        run: |
          echo "Running test suite..."
          if ! ./vendor/bin/pest --verbose; then
            echo "::error::Test suite failed! Check test output above for specific failures."
            exit 1
          fi
          echo "Test suite completed successfully."