name: TicketFlow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql

      - name: Set up Environment Variables
        run: |
          echo "APP_NAME=TicketFlow" >> $GITHUB_ENV
          echo "APP_ENV=testing" >> $GITHUB_ENV
          echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> $GITHUB_ENV
          echo "APP_URL=http://localhost" >> $GITHUB_ENV  
          echo "DB_CONNECTION=mysql" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV  
          echo "DB_DATABASE=test_db" >> $GITHUB_ENV
          echo "DB_USERNAME=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=" >> $GITHUB_ENV


      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-cache-${{ hashFiles('composer.lock') }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set up MySQL
        run: sudo service mysql start

      - name: Run Migrations
        run: php artisan migrate --env=testing

      - name: Run Pest Tests
        run: ./vendor/bin/pest