name: Deploy to Production

on:
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  pre-deployment-checks:
    #    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    env:
      PROD_DEPLOY_USER: ${{ secrets.PROD_DEPLOY_USER }}
      PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
      PROD_DEPLOY_PATH: ${{ secrets.PROD_DEPLOY_PATH }}
      PROD_GH_RUNNER_TO_EC2_KEY: ${{ secrets.PROD_GH_RUNNER_TO_EC2_KEY }}
      PROD_APP_URL: ${{ secrets.PROD_APP_URL }}
      PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
      PROD_DB_NAME: ${{ secrets.PROD_DB_NAME }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
      PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
      PROD_MEILISEARCH_HOST: ${{ secrets.PROD_MEILISEARCH_HOST }}
      PROD_MEILISEARCH_KEY: ${{ secrets.PROD_MEILISEARCH_KEY }}
      PROD_OPENROUTER_API_KEY: ${{ secrets.PROD_OPENROUTER_API_KEY }}
      PROD_JITSI_COOKIE: ${{ secrets.PROD_JITSI_COOKIE }}
      PROD_UNSPLASH_ACCESS_KEY: ${{ secrets.PROD_UNSPLASH_ACCESS_KEY }}
      PROD_UNSPLASH_RATE_LIMITING_ENABLED: ${{ secrets.PROD_UNSPLASH_RATE_LIMITING_ENABLED }}
      PROD_UNSPLASH_RATE_LIMITING_THRESHOLD: ${{ secrets.PROD_UNSPLASH_RATE_LIMITING_THRESHOLD }}
    steps:
      - name: Check for Required Secrets
        run: |
          MISSING_SECRETS=()
          REQUIRED_SECRETS=("PROD_DEPLOY_USER" "PROD_DEPLOY_HOST" "PROD_DEPLOY_PATH" "PROD_GH_RUNNER_TO_EC2_KEY"
          "PROD_APP_URL" "PROD_DB_HOST" "PROD_DB_NAME" "PROD_DB_PASSWORD" "PROD_DB_PORT" "PROD_DB_USER"
          "PROD_MEILISEARCH_HOST" "PROD_MEILISEARCH_KEY" "PROD_OPENROUTER_API_KEY" "PROD_JITSI_COOKIE" "PROD_UNSPLASH_ACCESS_KEY" "PROD_UNSPLASH_RATE_LIMITING_ENABLED" "PROD_UNSPLASH_RATE_LIMITING_THRESHOLD")

          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${!secret}" ]; then
              MISSING_SECRETS+=("$secret")
            fi
          done

          if [ ${#MISSING_SECRETS[@]} -ne 0 ]; then
            echo "❌ Missing required secrets: ${MISSING_SECRETS[@]}"
            exit 1
          fi

  deploy:
    needs: pre-deployment-checks
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_GH_RUNNER_TO_EC2_KEY }}

      - name: Trigger Remote Deployment
        env:
          CI: true
          GITHUB_SHA: ${{ github.sha }}
          PROD_DEPLOY_USER: ${{ secrets.PROD_DEPLOY_USER }}
          PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
          PROD_DEPLOY_PATH: ${{ secrets.PROD_DEPLOY_PATH }}
          PROD_APP_URL: ${{ secrets.PROD_APP_URL }}
          PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
          PROD_DB_NAME: ${{ secrets.PROD_DB_NAME }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_MEILISEARCH_HOST: ${{ secrets.PROD_MEILISEARCH_HOST }}
          PROD_MEILISEARCH_KEY: ${{ secrets.PROD_MEILISEARCH_KEY }}
          PROD_OPENROUTER_API_KEY: ${{ secrets.PROD_OPENROUTER_API_KEY }}
          PROD_JITSI_COOKIE: ${{ secrets.PROD_JITSI_COOKIE }}
          PROD_UNSPLASH_ACCESS_KEY: ${{ secrets.PROD_UNSPLASH_ACCESS_KEY }}
          PROD_UNSPLASH_RATE_LIMITING_ENABLED: ${{ secrets.PROD_UNSPLASH_RATE_LIMITING_ENABLED }}
          PROD_UNSPLASH_RATE_LIMITING_THRESHOLD: ${{ secrets.PROD_UNSPLASH_RATE_LIMITING_THRESHOLD }}
        run: |
          ssh -o StrictHostKeyChecking=no $PROD_DEPLOY_USER@$PROD_DEPLOY_HOST "export PROD_APP_URL=\"$PROD_APP_URL\" && \
          export PROD_DB_HOST=\"$PROD_DB_HOST\" && \
          export PROD_DB_NAME=\"$PROD_DB_NAME\" && \
          export PROD_DB_PASSWORD=\"$PROD_DB_PASSWORD\" && \
          export PROD_DB_PORT=\"$PROD_DB_PORT\" && \
          export PROD_DB_USER=\"$PROD_DB_USER\" && \
          export PROD_MEILISEARCH_HOST=\"$PROD_MEILISEARCH_HOST\" && \
          export PROD_MEILISEARCH_KEY=\"$PROD_MEILISEARCH_KEY\" && \
          export PROD_OPENROUTER_API_KEY=\"$PROD_OPENROUTER_API_KEY\" && \
          export PROD_JITSI_COOKIE=\"$PROD_JITSI_COOKIE\" && \
          export PROD_UNSPLASH_ACCESS_KEY=\"$PROD_UNSPLASH_ACCESS_KEY\" && \
          export PROD_UNSPLASH_RATE_LIMITING_ENABLED=\"$PROD_UNSPLASH_RATE_LIMITING_ENABLED\" && \
          export PROD_UNSPLASH_RATE_LIMITING_THRESHOLD=\"$PROD_UNSPLASH_RATE_LIMITING_THRESHOLD\" && \
          bash -l deploy.sh $GITHUB_SHA"