name: Deploy

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Production
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deployment_key
          chmod 600 ~/.ssh/deployment_key
          ssh-keyscan -H ticketflow.duckdns.org >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deployment_key ticket_flow@ticketflow.duckdns.org '
            cd code &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            npm ci &&
            npm run build &&
            php artisan down &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache &&
            php artisan migrate --force &&
            php artisan storage:link &&
            php artisan queue:restart &&
            php artisan scout:sync-index-settings &&
            php artisan cache:clear &&
            php artisan up
          '