# Triggers after successful CI run on main branch - ensures releases only happen after all tests pass
name: Release

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

# Prevents concurrent releases and cancels redundant runs
concurrency:
  group: release-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

# Required permissions for creating releases and updating issues/PRs
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    # Only proceed if the triggering CI workflow succeeded and was triggered by a push
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Fetches all history and tags for accurate versioning
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install Semantic Release
        run: npm install -D semantic-release@24.2.0

      # Generates semantic-release config with conventional commit parsing and customized release rules
      # Each commit type maps to a specific release type (major/minor/patch) or no release
      # Also configures how release notes are generated and how GitHub releases/issues are handled
      - name: Create Release Config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "plugins": [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "parserOpts": {
                    "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING", "DEPRECATED"],
                    "revertPattern": "^(?:Revert|revert:)\\s\"?([\\s\\S]+?)\"?\\s*This reverts commit (\\w*)\\.?",
                    "revertCorrespondence": ["header", "hash"],
                    "issuePrefixes": ["#"],
                    "headerPattern": "^(\\w*)(?:\\(([-\\w\\$\\.\\-\\* ]*)\\))?: (.*)$",
                    "headerCorrespondence": ["type", "scope", "subject"],
                    "breakingHeaderPattern": "^(\\w*)(?:\\(([-\\w\\$\\.\\-\\* ]*)\\))?!: (.*)$"
                  },
                  "releaseRules": [
                    { "breaking": true, "release": "major" },
                    { "type": "feat", "release": "minor" },
                    { "type": "fix", "release": "patch" },
                    { "type": "perf", "release": "patch" },
                    { "type": "security", "release": "patch" },
                    { "type": "docs", "release": "patch" },
                    { "type": "refactor", "release": "patch" },
                    { "type": "style", "release": "patch" },
                    { "type": "build", "release": "patch" },
                    { "type": "ci", "release": false },
                    { "type": "chore", "release": false },
                    { "type": "test", "release": false }
                  ]
                }
              ],
              [
                "@semantic-release/release-notes-generator",
                {
                  "preset": "angular",
                  "parserOpts": {
                    "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING", "DEPRECATED"],
                    "revertPattern": "^(?:Revert|revert:)\\s\"?([\\s\\S]+?)\"?\\s*This reverts commit (\\w*)\\.?",
                    "revertCorrespondence": ["header", "hash"],
                    "issuePrefixes": ["#"],
                    "headerPattern": "^(\\w*)(?:\\(([-\\w\\$\\.\\-\\* ]*)\\))?: (.*)$",
                    "headerCorrespondence": ["type", "scope", "subject"]
                  },
                  "writerOpts": {
                    "groupBy": "type",
                    "commitGroupsSort": [
                      "feat",
                      "perf",
                      "fix",
                      "security",
                      "refactor",
                      "style",
                      "docs",
                      "build",
                      "test",
                      "ci",
                      "chore"
                    ],
                    "commitsSort": ["scope", "subject"],
                    "noteGroupsSort": [
                      "BREAKING CHANGE",
                      "BREAKING CHANGES",
                      "BREAKING",
                      "DEPRECATED"
                    ],
                    "commitPartial": "* {{#if scope}}**{{scope}}**: {{/if}}{{subject}}\n{{~!-- commit link --}}{{#if hash}} {{#if @root.linkReferences}}([{{shortHash}}]({{commitUrlFormat}})){{else}}{{shortHash}}{{/if}}{{/if}}",
                    "footerPartial": "{{#if noteGroups}}\n{{#each noteGroups}}\n### {{title}}\n{{#each notes}}\n* {{#if commit.scope}}**{{commit.scope}}**: {{/if}}{{text}}\n{{/each}}\n{{/each}}{{/if}}\n"
                  },
                  "linkCompare": true,
                  "linkReferences": true
                }
              ],
              ["@semantic-release/github", {
                "successComment": ":tada: This issue has been resolved in version ${nextRelease.version} :tada:\n\nThe release is available on [GitHub release](${releases[0].url})",
                "failComment": ":rotating_light: This release failed due to the following errors:\n\n${errors.map(error => error.message).join('\n')}",
                "failTitle": "🚨 Automated Release Failed",
                "labels": ["released"],
                "releasedLabels": ["released"]
              }]
            ]
          }
          EOF

      # Executes semantic-release with the generated config
      # Analyzes commits, determines version bump, generates release notes, and creates GitHub release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release